# Generated by Django 2.1 on 2018-03-09 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
